# Generated by Django 4.1 on 2022-08-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0002_remove_answer_answers_answer_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answers',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
