# Generated by Django 4.1 on 2022-08-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0004_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizlet.question'),
        ),
    ]
