# Generated by Django 4.1 on 2022-08-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0006_remove_quiz_question_quiz_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer_correct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizlet.answer'),
        ),
    ]
