# Generated by Django 4.1 on 2022-08-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0007_quiz_answer_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answer_correct',
        ),
    ]
