# Generated by Django 4.1 on 2022-08-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0010_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questios',
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizlet.quiz'),
            preserve_default=False,
        ),
    ]
