# Generated by Django 4.1 on 2022-08-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0011_remove_quiz_questios_quesmodel_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='quiz',
        ),
    ]
