# Generated by Django 4.1 on 2022-08-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0015_question_remove_quiz_questions_delete_quesmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reverso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('percentage', models.IntegerField()),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('times', models.TimeField()),
                ('total', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizlet.quiz')),
            ],
        ),
    ]
