# Generated by Django 4.1 on 2022-08-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0016_reverso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reverso',
            name='times',
            field=models.IntegerField(),
        ),
    ]
