# Generated by Django 4.1 on 2022-08-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0017_alter_reverso_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reverso',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
    ]
