# Generated by Django 4.1 on 2022-08-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0018_alter_reverso_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reverso',
            name='times',
            field=models.IntegerField(null=True),
        ),
    ]
