# Generated by Django 4.1 on 2022-08-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0019_alter_reverso_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reverso',
            name='quiz',
        ),
    ]
