# Generated by Django 4.1 on 2022-08-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0020_remove_reverso_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='reverso',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizlet.quiz'),
            preserve_default=False,
        ),
    ]
