# Generated by Django 4.1.1 on 2022-10-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0023_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='reverso',
            name='dj',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
